name: Heartbeat Listener

on:
  repository_dispatch:
    types: [bot_heartbeat]

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Salvar timestamp
        run: |
          echo "$(date +%s)" > last_heartbeat.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando heartbeat"
